version: '3'

services:
  app1:
    build: .
    container_name: app1
    ports:
      - "4003:4001"

  app2:
    build: .
    container_name: app2
    ports:
      - "4002:4001"

  load_balancer:
    image: nginx:alpine
    container_name: load_balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
